services:
  bank:
    container_name: bank_frontend
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.DelveHotReload
    ports:
      - "5000:5000"
      - "40000:40000"
    environment:
      - ENV=docker
    volumes:
      - ./:/app  
    networks:
      - web_api

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - web_api

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - web_api
    
  otel_collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./monitoring/collector-gateway.yaml:/etc/collector-gateway.yaml
    command: ["--config=/etc/collector-gateway.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    networks:
      - web_api
    depends_on:
      - jaeger
    

    

networks:
  web_api:
    driver: bridge
    
  
