services:
  mongodb:
    container_name: mongo
    image: mongo:6.0.13
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "27017:27017"
    networks:
      - web_api
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db
  
  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - web_api


  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - web_api

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./pkg/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - web_api

  # rabbitmq:
  #   container_name: rabbitmq
  #   hostname: myrabbit
  #   image: rabbitmq:3.12.6-management-alpine
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  otel_collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./pkg/monitoring/collector-gateway.yaml:/etc/collector-gateway.yaml
    command: ["--config=/etc/collector-gateway.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    networks:
      - web_api
    depends_on:
      - jaeger
    
networks:
  web_api:
    driver: bridge
    
  
