FROM golang:1.20


WORKDIR /app

ENV config=docker

COPY .. /app

RUN go get github.com/githubnemo/CompileDaemon && \
  go get github.com/go-delve/delve/cmd/dlv

RUN go install github.com/githubnemo/CompileDaemon && \
  go install github.com/go-delve/delve/cmd/dlv

RUN go mod download


EXPOSE 5000 40000

ENTRYPOINT CompileDaemon --build="go build cmd/api/main.go" --command="dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient cmd/api/main.go"