global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: otel
    honor_labels: true
    static_configs:
      - targets: ['otel_collector:8888']

  - job_name: otel-collector
    static_configs:
      - targets: ['otel_collector:8889']